[theme]
primaryColor = "#1f77b4"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1A1D24"
textColor = "#FFFFFF"
font = "sans serif"

[client]
showErrorDetails = false

[logger]
level = "error"

[server]
maxUploadSize = 200
enableXsrfProtection = true
